### ISSUE TITLE
Always return refused or cancelled when call payment

### ISSUE THREAD

**Issue by baorongquan** [adyen-examples/adyen-golang-online-payments#2]
I already have created a ./.env file with my API key, Client Key - and add http://localhost:3000 as an origin for client key.
And I want get successful when call payment，But Always get refused or cancelled

**Comment by deepu105** [comment]
Do you have the error message from server?

**Comment by jlengrand** [comment]
@baorongquan Do you still need any help with this issue? Giving it a few days and then I will close it :)

**Comment by jlengrand** [comment]
Closing because stale. Please do reopen if needed @baorongquan
