### ISSUE TITLE
How to get a payment details using session flow without using `sessionId` & `sessionResult`?

### ISSUE THREAD

**Issue by arifmahmudrana** [adyen-examples/adyen-golang-online-payments#57]
I am planning to use session flow for simplicity but I can't find any documentation regarding how to get payment details without using `sessionId` & `sessionResult` using the `reference` provided on creating the session.

So I am creating a session
```go
// Adyen Go API Library v9.3.0
import (
  "context"
  "time"
  "github.com/adyen/adyen-go-api-library/v9/src/common"
  "github.com/adyen/adyen-go-api-library/v9/src/adyen"
  "github.com/adyen/adyen-go-api-library/v9/src/checkout"
)
// For the live environment, additionally include your liveEndpointUrlPrefix.
client := adyen.NewClient(&common.Config{
  ApiKey:      "ADYEN_API_KEY",
  Environment: common.TestEnv,
})

// Create the request object(s)
amount := checkout.Amount{
  Currency: "EUR",
  Value: 1000,
}

createCheckoutSessionRequest := checkout.CreateCheckoutSessionRequest{
  Reference: "YOUR_PAYMENT_REFERENCE",
  Mode: common.PtrString("hosted"),
  Amount: amount,
  MerchantAccount: "YOUR_MERCHANT_ACCOUNT",
  CountryCode: common.PtrString("NL"),
  ThemeId: common.PtrString("AZ1234567"),
  ReturnUrl: "https://your-company.com/checkout?shopperOrder=12xy..",
  ExpiresAt:  func() *time.Time { t, _ := time.Parse(time.RFC3339, "2023-05-18T10:15:30+01:00"); return &t }(),
}

// Make the API call
service := client.Checkout()
req := service.PaymentsApi.SessionsInput().IdempotencyKey("UUID").CreateCheckoutSessionRequest(createCheckoutSessionRequest)
res, httpRes, err := service.PaymentsApi.Sessions(context.Background(), req)
```
Then passing the `/sessions` response includes the URL (`url`) for the Hosted Checkout page to the customer. **How can I get the details of this session/payment using the reference later without the notification webhook?**

I have tried with their documentation(https://docs.adyen.com/online-payments/build-your-integration/sessions-flow/?programming_language=go) and example code(https://github.com/adyen-examples/adyen-golang-online-payments). 

https://stackoverflow.com/questions/78714765/how-to-get-a-payment-details-using-session-flow-without-using-sessionid-ses

**Comment by gcatanese** [comment]
Answered on [Stackoverflow](https://stackoverflow.com/a/78719958/9095551)
